### ISSUE TITLE
Wrong URL generation when using subpath in base URL

### ISSUE THREAD

**Issue by maikschneider** [sourcebroker/t3api#80]
Hey, great extension, love it!

I encountered a problem in the API route generation (`getFullApiBaseUrl`) and `TypoLinkHandler` when using a subpath in the `base` of site configuration:

```
base: 'https://my-site.ddev.site/suffix/'
languages:
  -
    title: English
    languageId: 0
    base: /
```

The generated API url becomes: `https://my-site.ddev.site/suffix/suffix/_api/something`, accessing it leads to a 404.

I guess the problem for the API route is in `getDefaultLanguageBasePath`, which returns `/suffix/` however it should be `/`. I don't know why the base of the default `SiteLanguage` equals the base of the `Site`, maybe the configuration should be used instead?

The TypolinkHandler has a quite similar problem: Both parameters used in `UrlService::forceAbsoluteUrl` contain the `suffix`. 

Can you reproduce and confirm the issue?

**Comment by klamparski** [comment]
Hi @maikschneider,

Thank you for reporting the issue. Unfortunately I'm not able to reproduce it. I tried it on our development instance using [t3apidemo](https://github.com/sourcebroker/t3apidemo) but both, API route and `TypoLinkHandler`, gives results as expected on TYPO3 v10 and v11. Which version of TYPO3 are you using?

Here is my full site configuration:

```yaml
base: https://v11.t3api.ddev.site/foo/
errorHandling: {  }
languages:
  -
    title: English
    languageId: 0
    base: /
    enabled: true
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-us
    direction: ltr
    flag: us
rootPageId: 1
routes: {  }
imports:
  -
    resource: 'EXT:t3api/Configuration/Routing/config.yaml'
```

in such case following URLs are accessible and gives correct responses:
https://v11.t3api.ddev.site/foo/_api
https://v11.t3api.ddev.site/foo/_api/news/news

Do you have any more hints to reproduce the issue?

**Comment by kszymukowicz** [comment]
@maikschneider 
I can not reproduce it on `release/3.0.0`.
I have:
```
base: 'https://v12.t3api.ddev.site/suffix'
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-us
    direction: ltr
    flag: us
    websiteTitle: ''
  -
    title: German
    enabled: true
    base: /de/
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    websiteTitle: ''
    navigationTitle: Deutsche
    hreflang: de-de
    direction: ltr
    fallbackType: strict
    fallbacks: ''
    flag: de
    languageId: 1
  -
```  
URL generated in response

For default language:
https://v12.t3api.ddev.site/suffix/_api/news/news
https://v12.t3api.ddev.site/suffix/news/sed-ut-perspiciatis-unde-omnis-iste-natus-error-sit-voluptatem-folder-a

For other language:
https://v12.t3api.ddev.site/suffix/de/_api/news/news
https://v12.t3api.ddev.site/suffix/de/news-de/sed-ut-perspiciatis-unde-omnis-iste-natus-error-sit-voluptatem-folder-a-de

I am closing this issue. 
Please open it if you can reproduce it on `release/3.0.0`.
